### ISSUE TITLE
Cannot get the revision information from the scm repository

### ISSUE THREAD

**Issue by Trollken-zz** [Mach5/supersonic#85]
Hi guys, and thanks for all your work.

I'd like to report  what seems to be a bug for me...
I followed all the steps from the INSTALL file, but i got a problem when trying to compile subsonic-main...

I got a build error.
Here are the traces...

root@HP1:~/supersonic-master# mvn -P full -pl subsonic-main -am install -e
  Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Reactor build order:
[INFO]   Supersonic
[INFO]   Supersonic Main
[INFO] ------------------------------------------------------------------------
[INFO] Building Supersonic
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [site:attach-descriptor {execution: default-attach-descriptor}]
[INFO] [dependency:analyze-only {execution: analyze}]
[INFO] Skipping pom project
[INFO] [install:install {execution: default-install}]
[INFO] Installing /root/supersonic-master/pom.xml to /root/.m2/repository/com/github/mach5/supersonic/supersonic/4.7.beta1/supersonic-4.7.beta1.pom
[INFO] ------------------------------------------------------------------------
[INFO] Building Supersonic Main
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [buildnumber:create {execution: default}]
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /root/supersonic-master/subsonic-main && git show
[INFO] Working directory: /root/supersonic-master/subsonic-main
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Cannot get the revision information from the scm repository :
Exception while executing SCM command.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Cannot get the revision information from the scm repository :
Exception while executing SCM command.
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot get the revision information from the scm repository :
Exception while executing SCM command.
        at org.codehaus.mojo.build.CreateMojo.getRevision(CreateMojo.java:727)
        at org.codehaus.mojo.build.CreateMojo.execute(CreateMojo.java:443)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
Caused by: org.apache.maven.scm.ScmException: Exception while executing SCM command.
        at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
        at org.apache.maven.scm.provider.git.AbstractGitScmProvider.executeCommand(AbstractGitScmProvider.java:290)
        at org.apache.maven.scm.provider.git.AbstractGitScmProvider.info(AbstractGitScmProvider.java:311)
        at org.codehaus.mojo.build.CreateMojo.info(CreateMojo.java:747)
        at org.codehaus.mojo.build.CreateMojo.getRevision(CreateMojo.java:694)
        ... 20 more
Caused by: java.lang.UnsupportedOperationException
        at org.apache.maven.scm.provider.git.gitexe.command.info.GitInfoCommand.executeCommand(GitInfoCommand.java:56)
        at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
        ... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Fri Jan 04 17:45:46 CET 2013
[INFO] Final Memory: 28M/50M
[INFO] ------------------------------------------------------------------------

How can i fix it ?
Thanks in advance ! :).

**Comment by jyofitch** [comment]
I had the same error building supersonic on OpenSUSE.  Here's how I addressed it:

Edit pom.xml. 

Find the lines that read:
               &lt;plugin>
                    &lt;groupId>org.codehaus.mojo&lt;/groupId>
                    &lt;artifactId>buildnumber-maven-plugin&lt;/artifactId>
                    &lt;version>1.0&lt;/version>
                &lt;/plugin>
and remove them.

I was able to compile and install Supersonic after doing this, but this 'fix' seems to have had a small, cosmetic side effect:  I get the message saying that a new version is available even though the latest version is installed.  I'm sure someone else can suggest a better approach...

**Comment by Trollken-zz** [comment]
Jyofitch, thank you sooooooooooooooooooo much !
It works like a charm ! :D.

Now, I can listen my music everywhere with D-Sub ! :D.

(for information, D-Sub is an open source client for subsonic you can get here : http://f-droid.org/repository/browse/?fdcategory=Multimedia&fdid=github.daneren2005.dsub :-) )

Thank you again ! :).

( I let the thread open, if someone got a better approach to suggest... ! )

**Comment by jyofitch** [comment]
I'm glad to hear that it worked for you, too!  :)

**Comment by Princee7** [comment]
Thanks a lot, worked for me too....

**Comment by adityanatani** [comment]
Thanks a ton. It worked.

**Comment by pbehghader** [comment]
Hi Guys- I have faced the same problem in another project.
How can I fix it (skip it, change the version, etc..) from command line, instead of changing pom.xml?

**Comment by hestonfer** [comment]
Add -Dmaven.buildNumber.skip to the command-line arguments to skip it.
